use crate::Kind;

// 装备基础数据 seed，会被同步进 equipment 表。
pub struct EquipmentSeed {
    pub short: &'static str,
    pub full: &'static str,
    pub kind: Kind,
    pub kind_label: &'static str,
    pub w: usize,
    pub h: usize,
    pub attack: f64,
    pub interval: f64,
    pub default_star: u8,
    pub properties: &'static str,
    pub attribute_tags: &'static [&'static str],
}

// 星级档位 seed，只记录真正会影响程序计算的数值。
pub struct StarSeed {
    pub short: &'static str,
    pub star: u8,
    pub attack: f64,
    pub interval: f64,
    pub normal_sword: i32,
    pub freeze_attack_bonus: Option<i32>,
    pub charged_enemy_sword: Option<i32>,
    pub properties: &'static str,
}

// 结构化动作 seed，是“装备规则 -> 程序执行”的桥梁。
pub struct ActionSeed {
    pub equipment_short: &'static str,
    pub trigger: &'static str,
    pub action: &'static str,
    pub target: &'static str,
    pub amount: Option<f64>,
    pub duration: Option<f64>,
    pub count: Option<i64>,
    pub source_text: &'static str,
    pub sort_order: i64,
}

// 面向人工查看的术语说明表。
pub struct AttributeTermSeed {
    pub term: &'static str,
    pub description: &'static str,
}

// 所有装备的静态目录，默认不会覆盖数据库里已有的非空人工维护内容。
pub const EQUIPMENT: &[EquipmentSeed] = &[
    EquipmentSeed {
        short: "百战",
        full: "百战魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始最大生命值+180点；受到治疗后：所有武器+16点攻击力（最多叠加10次）",
        attribute_tags: &["治疗"],
    },
    EquipmentSeed {
        short: "战神",
        full: "战神魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "受到治疗后：相邻武器加速2.5秒",
        attribute_tags: &["治疗", "加速"],
    },
    EquipmentSeed {
        short: "冻结",
        full: "冻结魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "自身被攻击时：冻结对手随机1件道具2秒",
        attribute_tags: &["冻结"],
    },
    EquipmentSeed {
        short: "天响",
        full: "天响魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始剑势+22点；振刀成功触发：所有道具充能1.5秒",
        attribute_tags: &["剑势", "振刀", "充能"],
    },
    EquipmentSeed {
        short: "冰髓",
        full: "冰髓护符",
        kind: Kind::Charm,
        kind_label: "护符",
        w: 2,
        h: 2,
        attack: 0.0,
        interval: 8.0,
        default_star: 4,
        properties: "发动间隔8.0；发动效果：冻结对手随机2件道具1.5秒；触发冻结时：剑势+10点",
        attribute_tags: &["冻结", "剑势"],
    },
    EquipmentSeed {
        short: "嗜血",
        full: "嗜血魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "暴击时：所有武器附加6%的吸血，最多叠加20次",
        attribute_tags: &["暴击", "吸血"],
    },
    EquipmentSeed {
        short: "破势",
        full: "破势魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "攻击命中时：对手剑势-12点",
        attribute_tags: &["剑势"],
    },
    EquipmentSeed {
        short: "缚命环",
        full: "缚命环",
        kind: Kind::Charm,
        kind_label: "护符",
        w: 2,
        h: 2,
        attack: 0.0,
        interval: 5.5,
        default_star: 4,
        properties: "发动间隔5.5；发动效果：治疗90点生命值，且所有武器攻击时附加40点治疗",
        attribute_tags: &["治疗"],
    },
    EquipmentSeed {
        short: "催破",
        full: "催破魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "普通攻击命中后触发：随机1件道具加速4秒",
        attribute_tags: &["普通攻击", "加速"],
    },
    EquipmentSeed {
        short: "锋锐",
        full: "锋锐魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "武器攻击命中后：减速对手随机1件道具4秒",
        attribute_tags: &["减速"],
    },
    EquipmentSeed {
        short: "续命术",
        full: "续命术魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "冻结触发时：治疗自身70点生命值",
        attribute_tags: &["冻结", "治疗"],
    },
    EquipmentSeed {
        short: "快意",
        full: "快意魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "发动冻结时：本魂玉相邻道具加速4秒",
        attribute_tags: &["冻结", "加速"],
    },
    EquipmentSeed {
        short: "穿颅",
        full: "穿颅魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始所有武器加速6秒，且相邻道具充能3秒",
        attribute_tags: &["加速", "充能"],
    },
    EquipmentSeed {
        short: "冰魄",
        full: "冰魄近战武器",
        kind: Kind::Weapon,
        kind_label: "近战武器",
        w: 1,
        h: 3,
        attack: 210.0,
        interval: 5.5,
        default_star: 4,
        properties: "星级属性：攻击力60/110/160/210，发动间隔7.0/6.5/6.0/5.5；多重触发1；普通攻击：造成等同于武器攻击力的伤害，剑势+16点，冻结对手随机2件道具2秒；每次触发冻结时：所有武器+20/35/50/65点攻击力，最多叠加7次",
        attribute_tags: &["武器攻击力", "普通攻击", "剑势", "冻结"],
    },
    EquipmentSeed {
        short: "吐纳",
        full: "吐纳术魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "受到治疗后：相邻武器+15点攻击力，最多叠加20次",
        attribute_tags: &["治疗"],
    },
    EquipmentSeed {
        short: "玄武",
        full: "玄武之力",
        kind: Kind::Potion,
        kind_label: "药品",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "使用次数1次；普通攻击命中后：最大生命值+200点，并治疗200点生命值，所有武器+40点攻击力，所有武器加速3秒",
        attribute_tags: &["治疗", "加速", "普通攻击"],
    },
    EquipmentSeed {
        short: "寒冰核",
        full: "寒冰核护符",
        kind: Kind::Charm,
        kind_label: "护符",
        w: 2,
        h: 2,
        attack: 0.0,
        interval: 6.0,
        default_star: 4,
        properties: "发动间隔6.0；发动效果：冻结对手随机1件道具3.5秒；普通攻击命中后：减速对手随机1件道具1秒",
        attribute_tags: &["冻结", "减速", "普通攻击"],
    },
    EquipmentSeed {
        short: "蜃景苞",
        full: "蜃景苞护符",
        kind: Kind::Charm,
        kind_label: "护符",
        w: 2,
        h: 2,
        attack: 0.0,
        interval: 7.5,
        default_star: 4,
        properties: "发动间隔7.5；发动效果：冻结对手随机1件道具1.1秒；触发冻结时：充能我方随机1件道具1.5秒",
        attribute_tags: &["冻结", "充能"],
    },
    EquipmentSeed {
        short: "铸盾",
        full: "铸盾魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "受到治疗后：护甲+45点",
        attribute_tags: &["治疗", "护甲"],
    },
    EquipmentSeed {
        short: "通达",
        full: "通达魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始所有道具加速2秒；我方道具被加速时：该魂玉相邻武器+18点攻击力，最多叠加20层",
        attribute_tags: &["加速"],
    },
    EquipmentSeed {
        short: "神将甲",
        full: "神将甲护甲",
        kind: Kind::Armor,
        kind_label: "护甲",
        w: 2,
        h: 3,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始护甲+300点，减伤+5%；已方道具被冻结或被振刀时：护甲+15点，并治疗15点生命值",
        attribute_tags: &["护甲", "减伤", "冻结", "振刀", "治疗"],
    },
    EquipmentSeed {
        short: "龙弧",
        full: "龙弧近战武器",
        kind: Kind::Weapon,
        kind_label: "近战武器（太刀）",
        w: 2,
        h: 2,
        attack: 75.0,
        interval: 6.0,
        default_star: 4,
        properties: "星级属性：攻击力30/45/60/75，发动间隔7.5/7.0/6.5/6.0；多重触发1；蓄力攻击：消耗28点剑势，造成3.7倍武器攻击力的伤害，对手剑势-10/12/14/16点，并冻结对手随机1件道具2秒；普通攻击：剑势不足时发动，造成等同于武器攻击力的伤害，剑势+10/12/14/16点",
        attribute_tags: &["武器攻击力", "蓄力攻击", "普通攻击", "剑势", "冻结"],
    },
    EquipmentSeed {
        short: "白虎之力",
        full: "白虎之力",
        kind: Kind::Potion,
        kind_label: "药品",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "使用次数1次；可使用1次；命中后：冻结对手所有道具3秒，所有武器+100点攻击力",
        attribute_tags: &["冻结", "武器攻击力"],
    },
    EquipmentSeed {
        short: "振魄",
        full: "振魄魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始剑势+20；蓄力攻击命中后：剑势+20，并冻结对手随机1件道具1秒",
        attribute_tags: &["剑势", "蓄力攻击", "冻结"],
    },
    EquipmentSeed {
        short: "混沌",
        full: "混沌魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "战斗初始剑势+20；普通攻击触发效果：剑势+8点；振刀成功触发效果：所有武器加速4秒",
        attribute_tags: &["剑势", "普通攻击", "振刀", "加速"],
    },
    EquipmentSeed {
        short: "烛神令",
        full: "烛神令",
        kind: Kind::Weapon,
        kind_label: "近战武器",
        w: 1,
        h: 3,
        attack: 160.0,
        interval: 6.0,
        default_star: 4,
        properties: "星级属性：攻击力55/90/125/160，发动间隔7.5/7.0/6.5/6.0；多重触发1；蓄力攻击：消耗24点剑势，造成2.25倍武器攻击力的伤害，生命恢复+4点；普通攻击：造成等同于武器攻击力的伤害，剑势+14点，生命恢复+4点；受到治疗后：本武器充能1秒；战斗初始剑势+20点",
        attribute_tags: &["武器攻击力", "蓄力攻击", "普通攻击", "治疗", "充能", "剑势"],
    },
    EquipmentSeed {
        short: "凌波",
        full: "凌波魂玉",
        kind: Kind::Soul,
        kind_label: "魂玉",
        w: 1,
        h: 1,
        attack: 0.0,
        interval: 0.0,
        default_star: 4,
        properties: "受到治疗后：减速对手随机1件道具4秒",
        attribute_tags: &["治疗", "减速"],
    },
];

// 目前只有少数装备实现了 1/2/3/4 星独立数值。
// 目前只有少数装备实现了 1/2/3/4 星独立数值。
pub const STAR_PROFILES: &[StarSeed] = &[
    StarSeed {
        short: "冰魄",
        star: 1,
        attack: 60.0,
        interval: 7.0,
        normal_sword: 16,
        freeze_attack_bonus: Some(20),
        charged_enemy_sword: None,
        properties: "1星：攻击力60，发动间隔7.0；普通攻击剑势+16；每次触发冻结时所有武器+20点攻击力，最多叠加7次",
    },
    StarSeed {
        short: "冰魄",
        star: 2,
        attack: 110.0,
        interval: 6.5,
        normal_sword: 16,
        freeze_attack_bonus: Some(35),
        charged_enemy_sword: None,
        properties: "2星：攻击力110，发动间隔6.5；普通攻击剑势+16；每次触发冻结时所有武器+35点攻击力，最多叠加7次",
    },
    StarSeed {
        short: "冰魄",
        star: 3,
        attack: 160.0,
        interval: 6.0,
        normal_sword: 16,
        freeze_attack_bonus: Some(50),
        charged_enemy_sword: None,
        properties: "3星：攻击力160，发动间隔6.0；普通攻击剑势+16；每次触发冻结时所有武器+50点攻击力，最多叠加7次",
    },
    StarSeed {
        short: "冰魄",
        star: 4,
        attack: 210.0,
        interval: 5.5,
        normal_sword: 16,
        freeze_attack_bonus: Some(65),
        charged_enemy_sword: None,
        properties: "4星：攻击力210，发动间隔5.5；普通攻击剑势+16；每次触发冻结时所有武器+65点攻击力，最多叠加7次",
    },
    StarSeed {
        short: "龙弧",
        star: 1,
        attack: 30.0,
        interval: 7.5,
        normal_sword: 10,
        freeze_attack_bonus: None,
        charged_enemy_sword: Some(10),
        properties: "1星：攻击力30，发动间隔7.5；蓄力消耗28剑势，造成3.7倍伤害，对手剑势-10并冻结随机1件道具2秒；剑势不足时普攻剑势+10",
    },
    StarSeed {
        short: "龙弧",
        star: 2,
        attack: 45.0,
        interval: 7.0,
        normal_sword: 12,
        freeze_attack_bonus: None,
        charged_enemy_sword: Some(12),
        properties: "2星：攻击力45，发动间隔7.0；蓄力消耗28剑势，造成3.7倍伤害，对手剑势-12并冻结随机1件道具2秒；剑势不足时普攻剑势+12",
    },
    StarSeed {
        short: "龙弧",
        star: 3,
        attack: 60.0,
        interval: 6.5,
        normal_sword: 14,
        freeze_attack_bonus: None,
        charged_enemy_sword: Some(14),
        properties: "3星：攻击力60，发动间隔6.5；蓄力消耗28剑势，造成3.7倍伤害，对手剑势-14并冻结随机1件道具2秒；剑势不足时普攻剑势+14",
    },
    StarSeed {
        short: "龙弧",
        star: 4,
        attack: 75.0,
        interval: 6.0,
        normal_sword: 16,
        freeze_attack_bonus: None,
        charged_enemy_sword: Some(16),
        properties: "4星：攻击力75，发动间隔6.0；蓄力消耗28剑势，造成3.7倍伤害，对手剑势-16并冻结随机1件道具2秒；剑势不足时普攻剑势+16",
    },
    StarSeed {
        short: "烛神令",
        star: 1,
        attack: 55.0,
        interval: 7.5,
        normal_sword: 14,
        freeze_attack_bonus: None,
        charged_enemy_sword: None,
        properties: "1星：攻击力55，发动间隔7.5；蓄力消耗24剑势造成2.25倍伤害并恢复4生命；普攻剑势+14并恢复4生命；受到治疗后本武器充能1秒；战斗初始剑势+20",
    },
    StarSeed {
        short: "烛神令",
        star: 2,
        attack: 90.0,
        interval: 7.0,
        normal_sword: 14,
        freeze_attack_bonus: None,
        charged_enemy_sword: None,
        properties: "2星：攻击力90，发动间隔7.0；蓄力消耗24剑势造成2.25倍伤害并恢复4生命；普攻剑势+14并恢复4生命；受到治疗后本武器充能1秒；战斗初始剑势+20",
    },
    StarSeed {
        short: "烛神令",
        star: 3,
        attack: 125.0,
        interval: 6.5,
        normal_sword: 14,
        freeze_attack_bonus: None,
        charged_enemy_sword: None,
        properties: "3星：攻击力125，发动间隔6.5；蓄力消耗24剑势造成2.25倍伤害并恢复4生命；普攻剑势+14并恢复4生命；受到治疗后本武器充能1秒；战斗初始剑势+20",
    },
    StarSeed {
        short: "烛神令",
        star: 4,
        attack: 160.0,
        interval: 6.0,
        normal_sword: 14,
        freeze_attack_bonus: None,
        charged_enemy_sword: None,
        properties: "4星：攻击力160，发动间隔6.0；蓄力消耗24剑势造成2.25倍伤害并恢复4生命；普攻剑势+14并恢复4生命；受到治疗后本武器充能1秒；战斗初始剑势+20",
    },
];

// 这里尽量只存“触发点 + 行为 + 参数”，让主程序做通用解释。
// 这里尽量只存“触发点 + 行为 + 参数”，让主程序做通用解释。
pub const EQUIPMENT_ACTIONS: &[ActionSeed] = &[
    ActionSeed {
        equipment_short: "冰魄",
        trigger: "active_use",
        action: "freezing_normal_weapon_attack",
        target: "enemy",
        amount: Some(1.0),
        duration: Some(2.0),
        count: Some(2),
        source_text: "冰魄",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "龙弧",
        trigger: "active_use",
        action: "charged_sword_control_weapon_attack",
        target: "enemy",
        amount: None,
        duration: None,
        count: None,
        source_text: "龙弧",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "烛神令",
        trigger: "active_use",
        action: "charged_healing_weapon_attack",
        target: "enemy",
        amount: None,
        duration: None,
        count: None,
        source_text: "烛神令",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "冰魄",
        trigger: "on_freeze_source",
        action: "add_freeze_attack_stack",
        target: "self_weapons",
        amount: Some(65.0),
        duration: None,
        count: Some(7),
        source_text: "冰魄",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "冰髓",
        trigger: "active_use",
        action: "freeze_random",
        target: "enemy_active",
        amount: None,
        duration: Some(1.5),
        count: Some(2),
        source_text: "冰髓",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "冰髓",
        trigger: "active_use",
        action: "sword",
        target: "self",
        amount: Some(10.0),
        duration: None,
        count: None,
        source_text: "冰髓",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "寒冰核",
        trigger: "active_use",
        action: "freeze_random",
        target: "enemy_active",
        amount: None,
        duration: Some(3.5),
        count: Some(1),
        source_text: "寒冰核",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "缚命环",
        trigger: "active_use",
        action: "mark_used",
        target: "self_item",
        amount: None,
        duration: None,
        count: None,
        source_text: "缚命环",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "缚命环",
        trigger: "active_use",
        action: "heal",
        target: "self",
        amount: Some(90.0),
        duration: None,
        count: None,
        source_text: "缚命环",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "蜃景苞",
        trigger: "active_use",
        action: "freeze_random",
        target: "enemy_active",
        amount: None,
        duration: Some(1.1),
        count: Some(1),
        source_text: "蜃景苞",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "蜃景苞",
        trigger: "active_use",
        action: "charge_random",
        target: "self_active",
        amount: Some(1.5),
        duration: None,
        count: None,
        source_text: "蜃景苞",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "百战",
        trigger: "battle_start",
        action: "max_hp",
        target: "self",
        amount: Some(180.0),
        duration: None,
        count: None,
        source_text: "百战魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "百战",
        trigger: "on_heal",
        action: "add_weapon_attack_stacking",
        target: "self_weapons",
        amount: Some(16.0),
        duration: None,
        count: Some(10),
        source_text: "百战",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "战神",
        trigger: "on_heal",
        action: "accelerate_adjacent_weapons",
        target: "self_adjacent_weapons",
        amount: None,
        duration: Some(2.5),
        count: None,
        source_text: "战神魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "冻结",
        trigger: "on_damaged",
        action: "freeze_random",
        target: "enemy_active",
        amount: None,
        duration: Some(2.0),
        count: Some(1),
        source_text: "冻结魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "天响",
        trigger: "battle_start",
        action: "start_sword",
        target: "self",
        amount: Some(22.0),
        duration: None,
        count: None,
        source_text: "天响魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "天响",
        trigger: "on_parry_success",
        action: "charge_all_active",
        target: "self_active",
        amount: Some(1.5),
        duration: None,
        count: None,
        source_text: "天响魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "破势",
        trigger: "on_attack_hit",
        action: "enemy_sword",
        target: "enemy",
        amount: Some(12.0),
        duration: None,
        count: None,
        source_text: "破势魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "缚命环",
        trigger: "on_attack_hit",
        action: "heal_if_used",
        target: "self",
        amount: Some(40.0),
        duration: None,
        count: None,
        source_text: "缚命环命中治疗",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "催破",
        trigger: "on_normal_hit",
        action: "accelerate_random",
        target: "self_active",
        amount: None,
        duration: Some(4.0),
        count: None,
        source_text: "催破魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "锋锐",
        trigger: "on_attack_hit",
        action: "slow_random",
        target: "enemy_active",
        amount: None,
        duration: Some(4.0),
        count: None,
        source_text: "锋锐魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "续命术",
        trigger: "on_freeze_triggered",
        action: "heal",
        target: "self",
        amount: Some(70.0),
        duration: None,
        count: None,
        source_text: "续命术",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "快意",
        trigger: "on_freeze_triggered",
        action: "accelerate_adjacent_active",
        target: "self_adjacent_active",
        amount: None,
        duration: Some(4.0),
        count: None,
        source_text: "快意魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "穿颅",
        trigger: "battle_start",
        action: "accelerate_weapons",
        target: "self_weapons",
        amount: None,
        duration: Some(6.0),
        count: None,
        source_text: "穿颅魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "穿颅",
        trigger: "battle_start",
        action: "charge_adjacent_active",
        target: "self_adjacent_active",
        amount: Some(3.0),
        duration: None,
        count: None,
        source_text: "穿颅魂玉",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "吐纳",
        trigger: "on_heal",
        action: "add_adjacent_weapon_attack_stacking",
        target: "self_adjacent_weapons",
        amount: Some(15.0),
        duration: None,
        count: Some(20),
        source_text: "吐纳",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "玄武",
        trigger: "on_normal_hit",
        action: "xuanwu_normal_hit",
        target: "self",
        amount: Some(200.0),
        duration: Some(3.0),
        count: Some(40),
        source_text: "玄武之力",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "寒冰核",
        trigger: "on_normal_hit",
        action: "slow_random",
        target: "enemy_active",
        amount: None,
        duration: Some(1.0),
        count: None,
        source_text: "寒冰核",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "铸盾",
        trigger: "on_heal",
        action: "armor",
        target: "self",
        amount: Some(45.0),
        duration: None,
        count: None,
        source_text: "铸盾魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "通达",
        trigger: "battle_start",
        action: "accelerate_all_active",
        target: "self_active",
        amount: None,
        duration: Some(2.0),
        count: None,
        source_text: "通达魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "通达",
        trigger: "on_accelerated",
        action: "add_adjacent_weapon_attack_stacking_if_adjacent_to_context",
        target: "self_adjacent_weapons",
        amount: Some(18.0),
        duration: None,
        count: Some(20),
        source_text: "通达魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "神将甲",
        trigger: "battle_start",
        action: "start_armor",
        target: "self",
        amount: Some(300.0),
        duration: None,
        count: None,
        source_text: "神将甲护甲",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "神将甲",
        trigger: "battle_start",
        action: "damage_reduction",
        target: "self",
        amount: Some(0.05),
        duration: None,
        count: None,
        source_text: "神将甲减伤",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "神将甲",
        trigger: "on_own_item_disabled",
        action: "armor",
        target: "self",
        amount: Some(15.0),
        duration: None,
        count: None,
        source_text: "神将甲",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "神将甲",
        trigger: "on_own_item_disabled",
        action: "heal",
        target: "self",
        amount: Some(15.0),
        duration: None,
        count: None,
        source_text: "神将甲",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "白虎之力",
        trigger: "on_attack_hit",
        action: "white_tiger_hit",
        target: "enemy_active",
        amount: Some(100.0),
        duration: Some(3.0),
        count: None,
        source_text: "白虎之力",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "振魄",
        trigger: "battle_start",
        action: "start_sword",
        target: "self",
        amount: Some(20.0),
        duration: None,
        count: None,
        source_text: "振魄魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "振魄",
        trigger: "on_charged_hit",
        action: "sword",
        target: "self",
        amount: Some(20.0),
        duration: None,
        count: None,
        source_text: "振魄",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "振魄",
        trigger: "on_charged_hit",
        action: "freeze_random",
        target: "enemy_active",
        amount: None,
        duration: Some(1.0),
        count: Some(1),
        source_text: "振魄",
        sort_order: 20,
    },
    ActionSeed {
        equipment_short: "混沌",
        trigger: "on_normal_attack",
        action: "sword",
        target: "self",
        amount: Some(8.0),
        duration: None,
        count: None,
        source_text: "混沌魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "混沌",
        trigger: "battle_start",
        action: "start_sword",
        target: "self",
        amount: Some(20.0),
        duration: None,
        count: None,
        source_text: "混沌魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "混沌",
        trigger: "on_parry_success",
        action: "accelerate_weapons",
        target: "self_weapons",
        amount: None,
        duration: Some(4.0),
        count: None,
        source_text: "混沌魂玉",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "烛神令",
        trigger: "battle_start",
        action: "start_sword",
        target: "self",
        amount: Some(20.0),
        duration: None,
        count: None,
        source_text: "烛神令",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "烛神令",
        trigger: "on_heal",
        action: "charge_self",
        target: "self_item",
        amount: Some(1.0),
        duration: None,
        count: None,
        source_text: "烛神令",
        sort_order: 10,
    },
    ActionSeed {
        equipment_short: "凌波",
        trigger: "on_heal",
        action: "slow_random",
        target: "enemy_active",
        amount: None,
        duration: Some(4.0),
        count: None,
        source_text: "凌波魂玉",
        sort_order: 10,
    },
];
// 术语表主要服务数据库人工维护和后续筛选，不直接参与战斗结算。
// 术语表主要服务数据库人工维护和后续筛选，不直接参与战斗结算。
pub const ATTRIBUTE_TERMS: &[AttributeTermSeed] = &[
    AttributeTermSeed {
        term: "治疗",
        description: "增加自身生命值",
    },
    AttributeTermSeed {
        term: "加速",
        description: "道具加速期间冷却时间读条增加100%",
    },
    AttributeTermSeed {
        term: "冻结",
        description: "道具冻结期间冷却时间暂停",
    },
    AttributeTermSeed {
        term: "充能",
        description: "立刻增加一件道具的读条进度",
    },
    AttributeTermSeed {
        term: "剑势",
        description: "剑势可用于发动蓄力攻击和振刀；蓄力攻击消耗剑势数量不等，振刀固定消耗50点剑势",
    },
    AttributeTermSeed {
        term: "振刀",
        description: "剑势>=50点时，消耗50点剑势，让对方本次蓄力攻击不生效，且硬直3秒",
    },
    AttributeTermSeed {
        term: "减速",
        description: "道具减速期间冷却时间读条减缓50%",
    },
    AttributeTermSeed {
        term: "减伤",
        description: "减少所有来源的伤害，不含中毒、灼伤伤害",
    },
    AttributeTermSeed {
        term: "暴击",
        description: "有一定几率造成2倍伤害。",
    },
    AttributeTermSeed {
        term: "灼伤",
        description: "每秒受到等同于当前灼伤层数的伤害，每秒层数减少10%。",
    },
    AttributeTermSeed {
        term: "中毒",
        description: "每秒受到等同于当前中毒层数的伤害，无视护甲。",
    },
    AttributeTermSeed {
        term: "蓄力攻击",
        description: "消耗剑势发动高额伤害攻击，可被振刀克制",
    },
    AttributeTermSeed {
        term: "武器攻击力",
        description: "直接影响武器造成的伤害数值。",
    },
    AttributeTermSeed {
        term: "普通攻击",
        description: "武器在非蓄力条件下发动的攻击。",
    },
    AttributeTermSeed {
        term: "护甲",
        description: "优先吸收受到的伤害。",
    },
    AttributeTermSeed {
        term: "吸血",
        description: "命中造成伤害后按比例回复生命值。",
    },
];
